! 2-harmonic-minor-et.scl
! Created using Scale Workshop 1.4.2
!
! https://sevish.com/scaleworkshop/?name=2-harmonic-minor-et&data=200.%0A300.%0A500.%0A700.%0A800.%0A1100.%0A1200.&freq=440&midi=69&vert=5&horiz=1&colors=white%20black%20white%20white%20black%20white%20black%20white%20white%20black%20white%20black&waveform=semisine&ampenv=organ
!
2-harmonic-minor-et
 7
!
 200.
 300.
 500.
 700.
 800.
 1100.
 1200.
