! 7-mixolydian-et.scl
! Created using Scale Workshop 1.4.2
!
! https://sevish.com/scaleworkshop/?name=7-mixolydian-et&data=200.%0A400.%0A500.%0A700.%0A900.%0A1000.%0A1200.&freq=440&midi=69&vert=5&horiz=1&colors=white%20black%20white%20white%20black%20white%20black%20white%20white%20black%20white%20black&waveform=semisine&ampenv=organ
!
7-mixolydian-et
 7
!
 200.
 400.
 500.
 700.
 900.
 1000.
 1200.
